version: '2'
services:
  homebridge:
    image: oznu/homebridge:ubuntu
    environment:
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
    ports:
      - 8581:8581
    volumes:
      - type: bind
        source: ./homebridge
        target: /homebridge

      # Development volumes
      - type: bind
        source: ./dist
        target: /homebridge/homebridge-open-sesame/dist
      - type: bind
        source: ./package.json
        target: /homebridge/homebridge-open-sesame/package.json
      - type: bind
        source: ./config.schema.json
        target: /homebridge/homebridge-open-sesame/config.schema.json
