version: '2'
services:
  homebridge:
    image: oznu/homebridge:ubuntu
    environment:
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
    ports:
      - 8581:8581
    volumes:
      - type: bind
        source: ./homebridge/config.json
        target: /homebridge/config.json
      - type: bind
        source: ./homebridge/package.json
        target: /homebridge/package.json
      - type: bind
        source: ./homebridge/persist
        target: /homebridge/persist
      - type: volume
        source: node_modules
        target: /homebridge/node_modules

      # Development volumes
      - type: bind
        source: ./dist
        target: /homebridge/homebridge-open-sesame/dist
      - type: bind
        source: ./package.json
        target: /homebridge/homebridge-open-sesame/package.json
      - type: bind
        source: ./config.schema.json
        target: /homebridge/homebridge-open-sesame/config.schema.json

volumes:
  node_modules:
